spring:
  datasource:
    url: jdbc:mysql://localhost:3303/api-project?serverTimezone=Asia/Seoul
    username: user_
    password: qwer1234!@#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  config:
    import:
      - classpath:/application/application-springdoc.yml
      - classpath:/application/application-mybatis.yml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
    serialization:
      write_dates_as_timestamps: false
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      resolve-lazily: true